name: Generate SLSA Provenance

on:
  release:
    types: [published]

permissions:
  id-token: write
  contents: read

jobs:
  generate-provenance:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up SLSA Generator
        uses: slsa-framework/slsa-github-generator@v1
        with:
          artifact_path: "subdomain_xss.rb"
          provenance_output: "slsa-provenance.json"

      - name: Upload Provenance to Release
        uses: softprops/action-gh-release@v2
        with:
          files: slsa-provenance.json

